[server]
enableXsrfProtection = false
enableCORS = false
headless = true
port = 8501

[theme]
base = "dark"

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
showSidebarNavigation = false

